dev.flow=testautomui,pubtestresults
cert.flow=testautomui,pubtestresults

# Prueba API
dev.stages.testautomapi.type=testing_api_artifactory
dev.stages.testautomapi.typeTest=api
dev.stages.testautomapi.commandParams=clean install

# Regression Test
dev.stages.testautomui.type=testing_ui_artifactory
dev.stages.testautomui.typeTest=regression
dev.stages.testautomui.commandParams=clean install

dev.stages.testautomui.tags=migracionDuoATrioTienda


# ####################### CERTIFICATION ####################### #

# Prueba API
cert.stages.testautomapi.type=testing_lib_artifactory
cert.stages.testautomapi.typeTest=api
cert.stages.testautomapi.commandParams=test

# Regression Test
cert.stages.testautomui.type=testing_ui_artifactory
cert.stages.testautomui.typeTest=regression
cert.stages.testautomui.commandParams=clean install
cert.stages.testautomui.tags=AltaTriomt,AltaMovilFinaciamientoTienda_CE,AltaSVABloqueHBO